### ISSUE TITLE
Add Ruby client generated from Swagger Codegen CLI

### ISSUE THREAD

**Issue by dfedorov-solace** [SolaceSamples/solace-samples-semp#13]
It is possible to generate Ruby clients using Swagger Codegen CLI (swagger-codegen-cli), and we should add description on how to do it and sample configurations.

**Comment by mdspielman** [comment]
Ruby would make a nice addition due to the applicability in configuration automation tools like Chef. So yes, I think this would be a good addition to our samples.

**Comment by dfedorov-solace** [comment]
Mark, assign it to me, please, I'll do it.

**Comment by mdspielman** [comment]
Balazs is going to work on this. Plan is to have a single gradle build that can conveniently build the client libraries in any language or in all languages and deploy them to a known subdirectory. The samples will then be updated to look for the client library in this location. The build should pull the SEMP schema from the dev portal and show how it can be updated to pull it from a Solace message router.

**Comment by dfedorov-solace** [comment]
Reference to my approach to it:
https://github.com/dfedorov-solace/solace-semp-config-begin/tree/master/ruby
