### ISSUE TITLE
Add Python client generated from Swagger Codegen CLI

### ISSUE THREAD

**Issue by dfedorov-solace** [SolaceSamples/solace-samples-semp#14]
It is possible to generate Python clients using Swagger Codegen CLI (swagger-codegen-cli), and we should add description on how to do it and sample configurations.

**Comment by mdspielman** [comment]
This would be a nice addition to the samples due to it's applicability in ansible for configuration automation.

**Comment by dfedorov-solace** [comment]
Mark, assign it to me, please, I'll do it.

**Comment by mdspielman** [comment]
Balazs is going to work on this. Plan is to have a single gradle build that can conveniently build the client libraries in any language or in all languages and deploy them to a known subdirectory. The samples will then be updated to look for the client library in this location. The build should pull the SEMP schema from the dev portal and show how it can be updated to pull it from a Solace message router.

**Comment by dfedorov-solace** [comment]
There is nothing convenient in using the single gradle build for everything and introducing a new third party dependency made who-knows-whom.

**Comment by wing328** [comment]
@dfedorov-solace you may want to give "OpenAPI Generator" (https://github.com/OpenAPITools/openapi-generator) a try, which comes with an official Gradle plugin.
