### ISSUE TITLE
Fix online CustDoc link to Client Profile

### ISSUE THREAD

**Issue by bczoma** [SolaceSamples/solace-samples-semp#16]
+docs-client-profile: http://docs.solace.com/Features/Client-Authorization.htm#client_authentication_and_authorization_2866343001_219397 

This link will break easily. Should work with Solace docs team to get a permanent link to this location.

**Comment by Mrc0113** [comment]
Closing as this is old. Also any broken links have been resolved in recent tutorials refresh + broken link checker runs in an automated fashion.
