### ISSUE TITLE
Build the Java/Python/Ruby project from the root directory.

### ISSUE THREAD

**Issue by evenjessie** [SolaceSamples/solace-samples-semp#28]
It will be nice if we could build the Java/Python/Ruby project with Gradle from the root folder "solace-samples-semp/".

**Comment by mdspielman** [comment]
Agree. This would be a nice improvement to the samples.

**Comment by bczoma** [comment]
The original reason for not building all from root was the assumption that a particular audience would only be interested in one technology at a time. Building all may take some time.

At the same time one could have the option to build all and perhaps individually if that makes sense or one could drop the individual builds.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
