### ISSUE TITLE
Could not find method leftShift() for arguments

### ISSUE THREAD

**Issue by seojoonha** [SolaceSamples/solace-samples-semp#43]
Hi,
When I try to build the program, this error occurs.

seo@DESKTOP-LGNQKUK MINGW64 ~
$ cd solace-samples-semp/java

seo@DESKTOP-LGNQKUK MINGW64 ~/solace-samples-semp/java (master)
$ gradlew buildSempLib

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\seo.DESKTOP-LGNQKUK\solace-samples-semp\java\build.gradle' line: 78

* What went wrong:
A problem occurred evaluating root project 'java'.
> Could not find method leftShift() for arguments [build_2z0clg24n8i2w8vgplyrxzpmx$_run_closure8@1b80f599] on task ':createAllStartScripts' of type org.gradle.api.DefaultTask.

Is there anything I can do??

**Comment by mrpilgrim** [comment]
As per [https://stackoverflow.com/questions/55793095/could-not-find-method-leftshift-for-arguments-after-updating-studio-3-4](url) 

build.gradle needs to be modified to replace `<< {` with `doLast { }`

This is due to `<< {` being deprecated in Gradle V4 and removed in V5

**Comment by TamimiGitHub** [comment]
Fixed in #49
