### ISSUE TITLE
What does 'message spool data not available' mean?

### ISSUE THREAD

**Issue by spierepf** [SolaceSamples/solace-samples-semp#47]
Trying to programmatically create a queue using the solace python swagger api, and I keep getting this error:

```
E           semp_client.rest.ApiException: (400)
E           Reason: Bad Request
E           HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 09 Sep 2020 14:24:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Solace_VMR/9.6.0.32', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Authorization, Content-Type, X-Requested-With', 'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS', 'Strict-Transport-Security': 'max-age=31536000', 'Cache-Control': 'no-store'})
E           HTTP response body: {
E               "meta":{
E                   "error":{
E                       "code":412,
E                       "description":"Problem with reading: message spool data not available",
E                       "status":"MESSAGE_SPOOL_DATA_NOT_AVAILABLE"
E                   },
E                   "request":{
E                       "method":"GET",
E                       "uri":"http://localhost:32831/SEMP/v2/config/msgVpns/message_vpn_name/queues"
E                   },
E                   "responseCode":400
E               }
E           }

semp_client/semp_client/rest.py:228: ApiException
```

Can anyone explain the meaning of this response?

**Comment by aaron-613** [comment]
Now that this samples repo is able to be built again, I went to Support to get an answer on this long-outstanding question.  Specifically:

> what does: "Problem with reading: message spool data not available" mean?

_It means when you're trying to perform an action on the spooled messages but the backend filesystem configured for backing up those spooled messages is not mounted._

> I'm figuring they're either querying a broker that is not up yet, maybe a standby broker, or something along those lines.  Any clue?

_Yes you are right. Normally, the error will be returned when the message-spool is not AD-Active. It could be either disabled or AD-Not Ready or Standby._


So I'm guessing that either the broker is not started up yet, or is not configured for Guaranteed Messaging, or is querying the standby broker in an HA-Pair.

Without additional info on the broker configuration/status and SEMP command submitted, it will be hard to determine exactly what.

**Comment by aaron-613** [comment]
Closing.
