### ISSUE TITLE
Build Fails with Latest swagger-codegen + Gradle Version

### ISSUE THREAD

**Issue by PeacelynPoppy** [SolaceSamples/solace-samples-semp#48]
Can this sample be improved so that it is compatible with latest Gradle/ Latest Java and with the recent swagger-codegen stable version as the current build attempts fails due to compatibility issues with Gradle - 

//buildSempLib.execute()
buildSempLib Task couldnt be invoked with the Latest Gradle version.

**Comment by aaron-613** [comment]
Ok.  One of the big problems here I think it that everything seems to be out of date.  All the libraries that the build file is referencing are about one major version number moved on.  I think this isn't as simple as tweaking a few values.  I'm wondering if it might be better to start from scratch..?

**Comment by aaron-613** [comment]
```$ ../gradlew build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed
```
Well, that's progress.  Managed to get it built manually, using the swagger codegen from the command line.  I guess I need to figure out what's changed in Gradle that the wacky build script from 2.x doesn't work anymore.

Maybe we should consider switching to OpenAPI Generator?
> OpenAPI Generator is a fork of Swagger Codegen capable of generating 50+ clients from any OpenAPI Specification 2.0/3.x documents.
> Whereas Swagger Codegen is maintained by SmartBear, OpenAPI Generator is maintained by a community that includes more than 40 of the top contributors and template creators of Swagger Codegen as founding team members.

https://www.baeldung.com/spring-boot-rest-client-swagger-codegen

**Comment by aaron-613** [comment]
https://github.com/SolaceSamples/solace-samples-semp/pull/49

**Comment by TamimiGitHub** [comment]
Thanks for looking into this Aaron 🙏
