### ISSUE TITLE
Docs: other JSON libraries available.

### ISSUE THREAD

**Issue by TomFairbairn** [SolaceSamples/solace-samples-semp#9]
The examples use Google GSON to parse JSON.  Add a comment noting that other JSON libraries are available.

**Comment by TomFairbairn** [comment]
I will fix.

**Comment by mdspielman** [comment]
Tom, can you clarify the issue here. Which tutorial are you specifically talking about and which discussion.

**Comment by TomFairbairn** [comment]
Mark, yes specifically https://github.com/SolaceSamples/solace-samples-semp/blob/master/docs/_tutorials/java-client.md#error-handling.  Although Swagger uses Gson, there is no reason why a user couldn't use their own JSON parser which may already be in _their_ dependancies.

Other samples (e.g. https://github.com/SolaceSamples/solace-samples-semp/blob/master/src/main/java/com/solace/samples/JavaClientSample.java) use GSON in the same way, but I don't propose to change them.  Once past the introductory material and in to the full samples, I would hope users would understand.
